### PR TITLE
Rounding fix

### PR DESCRIPTION
**Pull request by Rustymage**

### CODE REVIEW

**Comment by Rustymage** [comment]
https://github.com/stevequinn/photoborder/issues/5

**Comment by Rustymage** [comment]
Tested this on a few images with success.

**Comment by Rustymage** [comment]
https://github.com/stevequinn/photoborder/pull/6/commits/a9419c444853d75e97c6f79c12e5b8c3e1f5fb44

From:
image

To:
image

**Comment by stevequinn** [comment]
This is great, nice work. Love the Exif data persist upgrade too!

**Pull request merged**
